---

helm_repo:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: haproxytech
    url: https://haproxytech.github.io/helm-charts
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: jetstack
    url: https://charts.jetstack.io
  - name: flannel
    url: https://flannel-io.github.io/flannel/
  - name: argo-repo
    url: https://argoproj.github.io/argo-helm 

default_chart:
  - name_release: metal-lb
    name_chart: metallb/metallb
    namespace: metallb-system
    version:  0.15.2

chart_with_value:
  - name_release: argocd
    name_chart: argo-repo/argo-cd
    namespace: argocd
    version: 8.1.2
  - name_release: haproxy
    name_chart: haproxytech/kubernetes-ingress
    namespace: haproxy-controller
    version:  1.44.3
  - name_release: cert-manager
    name_chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.18.0

flannel_chart:
  name_release: flannel
  name_chart: flannel/flannel
  namespace: flannel
  version: 0.27.0