---

- hosts: all,!lb-node
  become: true
  tags: setup-pre-cluster
  roles:
    - {name: setup-pre-k8s, tags: [setup]}


- hosts: lb-node
  become: true
  tags: setup-lb
  roles:
    - {name: packages-lb, tags: [setup]}
    - {name: haproxy, tags: [haproxy]}

- hosts: all,!lb-node
  become: true
  serial: 1
  order: sorted
  roles:
    - {name: desinstall-k8s, tags: [new-install, desinstall, never]}

- hosts: all,!lb-node
  become: true
  serial: 1
  order: sorted
  roles:
    - {name: k8s, tags: [new-install, k8s]}