---

- hosts: master,worker
  become: true
  tags: setup-pre-cluster
  roles:
    - {name: setup-pre-k8s, tags: [pre-k8s]}


- hosts: lb
  become: true
  tags: setup-lb
  roles:
    - {name: packages-lb, tags: [pre-k8s]}
    - {name: haproxy, tags: [pre-k8s]}

- hosts: master,worker
  become: true
  serial: 1
  order: sorted
  roles:
    - {name: desinstall-k8s, tags: [new-install, desinstall, never]}

- hosts: master,worker
  become: true
  serial: 1
  order: sorted
  roles:
    - {name: k8s, tags: [new-install, k8s]}