---

- name: Create containerd folder
  ansible.builtin.file:
    name: /etc/containerd/
    owner: root
    group: root
    mode: 0644
    state: directory

- name: Delete Container default config
  ansible.builtin.copy:
    src: files/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644
  notify: Restart containerd

- name: enable additonal module for the linus kernel
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Configure systctl
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/kubernetes.conf
  with_dict: '{{ sysctl_config }}'

- name: modification de l'etc/hosts pour le endpoint kube
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: '127.0.0.1 localhost'
    line: "10.0.0.8 {{ control_plane_endpoint }}"

