---


- name : Install packages
  apt:
    pkg:
      - apt-transport-https
      - curl
      - ca-certificates
      - gpg
      - kubectl
      - kubeadm
      - kubelet
      - containerd
      - python3-pip


- name: Hold kube services 
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubectl
    - kubeadm
    - kubelet
