---

- name: add the new nodes to the cluster
  when: inventory_hostname != "master[0]" and node_type == "master"
  block:
    - name: create new certificate key for control plane
      command: kubeadm init phase upload-certs --upload-certs
      register: kubeadm_cert
      delegate_to: "master-0.k8s.assouman"

    - name: set fact for kubeadm join command for the worker node and control-plane node
      set_fact:
        kubeadm_cert_key: "{{ kubeadm_cert.stdout_lines[2]}}"
      delegate_to: "master-0.k8s.assouman"

- name:  add the new nodes to the cluster
  block:
    - name: create join command for the following nodes
      command: kubeadm token create --print-join-command
      register: kubeadm_join_command_initial
      delegate_to: "master-0.k8s.assouman"

    - name: set fact for kubeadm join command for the worker node and control-plane node
      set_fact:
        cert_key: "{{ (node_type == 'master') | ternary('--certificate-key {{ kubeadm_cert_key }} --control-plane','') }}"
      delegate_to: "master-0.k8s.assouman"
    
    - name: execute the join command
      vars: 
        kubeadm_join_command: "{{ kubeadm_join_command_initial.stdout }} {{ cert_key }}"
      command:  "{{ kubeadm_join_command }}"
      



