---

- name: Creation of the .kube directory
  file:
    path: /home/debian/.kube
    owner: debian
    group: debian
    mode: 0750
    state: directory

- name: Copy kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/debian/.kube/config
    remote_src: true
    owner: debian
    group: debian
    mode: 0650


- name: Copy kube config for node proxmox
  fetch:
    src: /home/debian/.kube/config
    dest: /home/debian/.kube/config
    owner: debian
    group: debian
    flat: true
    mode: 0650
