---

name: release-management

on:
  push:
    branches:
      - main
      - 'feat/**'
  pull_request:
    branches:
      - 'main'

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    if: github.event_name == 'pull_request'
    steps:
      - name: update
        shell: bash
        run: apt-get update
      - name: install git
        shell: bash
        run: apt-get install git -y
      - name: Clone the repo manually
        shell: bash
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git clone https://github.com/${GITHUB_REPOSITORY} .
          git fetch --all --tags     
      - name: check changelog
        shell: bash
        run: |
           cd /__w/homelab-k8s-cluster/homelab-k8s-cluster
           ls -al
           NEW_CHANGELOG=$(git diff CHANGELOG.md ) 
           if [ -z "$NEW_CHANGELOG" ]; then
             echo "there are no new version because the changelog is empty"
             exit 1
            fi
      - name: get old version
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          OLD_TAG=$(git tag -l | tail -n1)
          if [ -z "$OLD_TAG" ]; then
            echo "it is strange, you do not have previous tag"
            exit 1
          fi
      - name: get new version
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          NEW_TAG=$( git diff CHANGELOG.md | grep Version | grep -oE '[1-9]*[0-9]*\.[1-9]*[0-9]\.[1-9][0-9]*')
          if [ -z "$NEW_TAG" ]; then
            echo "How the fuck, am i suppose to create a new tag, you did not precise one"
            exit 1
          fi

  publish-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: My first stupid step - check out repository
        uses: actions/checkout@v4
      - uses: './actions/setup'
      - uses: './actions/publish'
