---

name: release-management

on:
  push:
    branches:
      - main
      - 'feat/**'
  pull_request:
    branches:
      - 'main'

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    if: github.event_name == 'pull_request'
    steps:
      - name: My first stupid step - check out repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - uses: './actions/setup'
      - uses: './actions/check'
  publish-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: My first stupid step - check out repository
        uses: actions/checkout@v4
      - uses: './actions/setup'
      - uses: './actions/publish'
